name: Deploy mdBook
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install mdBook
        run: (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)

      - name: Build
        run: mdbook build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: book
          target-folder: book
          clean: true